# Generated by Django 5.2.16 on 2026-07-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Состав заказа', 'verbose_name_plural': 'Состав заказов'},
        ),
    ]
