# Generated by Django 5.2.16 on 2026-08-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_product_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurant_menu_item',
        ),
    ]
