# Generated by Django 5.2.16 on 2026-08-05 12:41

from django.db import migrations


def set_order_item_prices(apps, schema_editor):

    OrderItem = apps.get_model("foodcartapp", "OrderItem")

    for item in OrderItem.objects.select_related("product").iterator():
        item.price = item.product.price
        item.save(update_fields=["price"])


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0043_alter_orderitem_options_alter_orderitem_order"),
    ]

    operations = [
        migrations.RunPython(set_order_item_prices),
    ]
