# Generated by Django 5.2.16 on 2026-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20260805_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('in_progress', 'На сборке'), ('ready', 'Готов к доставки'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен'), ('canceled', 'Отменён'), ('returned', 'Возврат'), ('erorr', 'Ошибка')], db_index=True, default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Адрес клиента'),
        ),
    ]
