# Generated by Django 5.2.16 on 2026-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличными'), ('card', 'картой'), ('QR', 'QR-кодом'), ('online', 'онлайн')], db_index=True, default='не выбрано', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
